services:
  - docker

before_install:
- docker pull linuxianer99/ovlinux-build
- mkdir build
- docker run -d -it --rm --name ovbuild -v $(pwd)/build:/workdir linuxianer99/ovlinux-build --workdir=/workdir
- docker exec -it ovbuild repo init -u git://github.com/linuxianer99/ovlinux-manifest.git -b warrior
- docker exec -it ovbuild repo sync


script:
- ls -al
- pwd
- cd build
- pwd
- ls -al
