name: Build openvario image

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Pull docker
      run: docker pull linuxianer99/ovlinux-build
    
    - name: Init repo
      run: docker run --rm --name ovbuild -v ${{ github.workspace }}:/workdir linuxianer99/ovlinux-build --workdir=/workdir repo init -u git://github.com/linuxianer99/ovlinux-manifest.git -b warrior
    
    - name: Repo Sync
      run: docker run --rm --name ovbuild -v ${{ github.workspace }}:/workdir linuxianer99/ovlinux-build --workdir=/workdir repo sync
        
    - name: Run bitbake
      run: docker run --rm --name ovbuild -v ${{ github.workspace }}:/workdir linuxianer99/ovlinux-build --workdir=/workdir ./build.sh
